backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name="backend"
urlpatterns = [
    url(r'index/$', views.List_user, name='backend_index'),
    url(r'api-info/$', views.Api_iot, name='backend_api'),
    url(r'account/$', views.Acc_manager, name='backend_account'),
    url(r'login/$', views.Login, name='backend_login'),
    url(r'detail/(?P<node_id>[0-9]+)/$', views.Admin_detail, name='backend_detail'),
]

fog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('iotnode.urls')),
    url(r'^', include('showfront.urls')),
    url(r'^backend/', include('backend.urls')),
]

showfront/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name="showfront"
urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^technology/$', views.Technology, name='technology'),
    url(r'^blog/$', views.Technology_single, name='blog'),
    url(r'^about/$', views.About, name='about'),
]

showfront/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

showfront/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
@csrf_exempt
def Home(request):
    return render(request,'showfront/home.html')

@csrf_exempt
def Technology(request):
    return render(request,'showfront/technology.html')

@csrf_exempt
def Technology_single(request):
    return render(request,'showfront/blog-single.html')

@csrf_exempt
def About(request):
    return render(request,'showfront/about.html')

showfront/templates/showfront/about.html
{% load staticfiles  %}
<!DOCTYPE html>
<html dir="ltr" lang="en-TW">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="ITLab-IoT team | NCKU" />
    <link rel="shortcut icon" href="{% static "showfront/images/favicon.ico" %}">

	<!-- Stylesheets
	============================================= -->
	<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/bootstrap.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/style.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/dark.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/font-icons.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/animate.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/magnific-popup.css" %}" type="text/css" />

	<link rel="stylesheet" href="{% static "showfront/css/responsive.css" %}" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Here goes your colors.css
	============================================= -->
	<link rel="stylesheet" href="{% static "showfront/css/colors.css" %}" type="text/css" />
    
      <!-- custome css
	============================================= -->
	<link rel="stylesheet" href="{% static "showfront/css/2016.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "showfront/css/basic.css" %}" type="text/css" />
    
    
	<!--[if lt IE 9]>
		<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
	<![endif]-->

	<!-- External JavaScripts
	============================================= -->
	<script type="text/javascript" src="{% static "showfront/js/jquery.js" %}"></script>
	<script type="text/javascript" src="{% static "showfront/js/plugins.js" %}"></script>

	<!-- Document Title
	============================================= -->
	<title>ITLab-IoT team | NCKU</title>

</head>

<body class="stretched">

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Header
		============================================= -->
		<header id="header" class="full-header">

			<div id="header-wrap">

				<div class="container clearfix">

					<div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

					<!-- Logo
					============================================= -->
					<div id="logo">
						<a href="{% url "showfront:home" %}" class="standard-logo" data-dark-logo="{% static "showfront/images/logo-dark.png" %}"><img src="{% static "showfront/images/logo.png" %}" alt="NCKU Logo"></a>
						<a href="{% url "showfront:home" %}" class="retina-logo" data-dark-logo="{% static "showfront/images/logo-dark@2x.png" %}"><img src="{% static "showfront/images/logo@2x.png" %}" alt="NCKU Logo"></a>
					</div><!-- #logo end -->

					<!-- Primary Navigation
					============================================= -->
					<nav id="primary-menu">

						<ul>
							<li><a href="{% url "showfront:home" %}"><div>HOME</div></a>
							
							</li>
							<li><a href="{% url "showfront:technology" %}"><div>Technology</div></a>
							
							</li>
                            
                            <li><a href="{% url "backend:backend_login" %}"><div>Admin</div></a>
							
							</li>
                            
                            <li class="current"><a href="{% url "showfront:about" %}"><div>About Us</div></a>
							
							</li>
                            
							
						</ul>

					

						

					</nav><!-- #primary-menu end -->

				</div>

			</div>

		</header><!-- #header end -->

		

		<!-- Content
		============================================= -->
		<section id="content">

			<div class="content-wrap">

				<div class="container clearfix">

				

					<div class="heading-block center">
						<h2>About Us</h2>
						<span>Our Team Members who have contributed immensely to our Growth</span>
					</div>

					<div class="row clearfix">

						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar2.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>楊竹星</h4><span>Professor</span></div>
									<div class="team-content">
										<p>	國立成功大學電機系教授 <br/>
											國立成功大學電腦與通信工程研究所教授 
											
										</p>
									</div>
									
								</div>
							</div>
						</div>

						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>倪瑞忠</h4><span>PHD</span></div>
									<div class="team-content">
										<p>負責整個團隊的運行、規劃<br/>
											國立成功大學電機所博士 
									
										</p>
									</div>
									
								</div>
							</div>
						</div>

						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>李世雄</h4><span>PHD</span></div>
									<div class="team-content">
										<p>
										負責雲端服務指導<br />
										國立成功大學電機所博士
										</p>
									</div>
									
								</div>
							</div>
						</div>

						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>夏年</h4><span>PHD</span></div>
									<div class="team-content">
										<p>
											負責M2M通訊研究<br />
											國立成功大學電腦與通信工程研究所博士
										</p>
									</div>
									
								</div>
							</div>
						</div>
						
						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>趙永剛</h4><span>Master</span></div>
									<div class="team-content">
										<p>
											負責雲端服務實作<br />
											國立成功大學電腦與通信工程研究所碩士
										</p>
									</div>
									
								</div>
							</div>
						</div>
						
						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>許程堯</h4><span>Master</span></div>
									<div class="team-content">
										<p>
											負責藍牙通訊實作<br />
											國立成功大學電機所碩士
										</p>
									</div>
									
								</div>
							</div>
						</div>
						
						<div class="col-md-6 bottommargin">
							<div class="team team-list clearfix">
								<div class="team-image">
									<img src="{% static "showfront/images/team/avatar1.jpg" %}" alt="">
								</div>
								<div class="team-desc">
									<div class="team-title"><h4>朱家毅</h4><span>Master</span></div>
									<div class="team-content">
										<p>
											負責MCU實作<br />
											國立成功大學電腦與通信工程研究所碩士
										</p>
									</div>
									
								</div>
							</div>
						</div>
						
						
					</div>

				</div>

			

			</div>

		</section><!-- #content end -->

			<!-- Footer
		============================================= -->
		<footer id="footer" class="dark">

			

			<!-- Copyrights
			============================================= -->
			<div id="copyrights">

				<div class="container clearfix">

					<div class="col_half">
						Copyrights &copy; 2016 All Rights Reserved by ITLab-IoT team | NCKU.<br>
						



				</div>
<div class="col_half col_last tright">
						
<i class="icon-envelope2"></i> steven.ncku@gmail.com
						
					</div>
			</div><!-- #copyrights end -->

		</footer><!-- #footer end -->


	</div><!-- #wrapper end -->

	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- Footer Scripts
	============================================= -->
	<script type="text/javascript" src="{% static "showfront/js/functions.js" %}"></script>

</body>
</html>

showfront/templates/showfront/technology.html
{% load staticfiles  %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="ITLab-IoT team | NCKU" />
    <link rel="shortcut icon" href="{% static "showfront/images/favicon.ico" %}">

	<!-- Stylesheets
	============================================= -->
	<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/bootstrap.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/style.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/dark.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/font-icons.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/animate.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "showfront/css/magnific-popup.css" %}" type="text/css" />

	<link rel="stylesheet" href="{% static "showfront/css/responsive.css" %}" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Here goes your colors.css
	============================================= -->
	<link rel="stylesheet" href="{% static "showfront/css/colors.css" %}" type="text/css" />
    
      <!-- custome css
	============================================= -->
	<link rel="stylesheet" href="{% static "showfront/css/2016.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "showfront/css/basic.css" %}" type="text/css" />
    
    
	<!--[if lt IE 9]>
		<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
	<![endif]-->

	<!-- External JavaScripts
	============================================= -->
	<script type="text/javascript" src="{% static "showfront/js/jquery.js" %}"></script>
	<script type="text/javascript" src="{% static "showfront/js/plugins.js" %}"></script>

	<!-- Document Title
	============================================= -->
	<title>ITLab-IoT team | NCKU</title>

</head>

<body class="stretched">

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Header
		============================================= -->
		<header id="header" class="full-header">

			<div id="header-wrap">

				<div class="container clearfix">

					<div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

					<!-- Logo
					============================================= -->
					<div id="logo">
						<a href="{% url "showfront:home" %}" class="standard-logo" data-dark-logo="{% static "showfront/images/logo-dark.png" %}"><img src="{% static "showfront/images/logo.png" %}" alt="NCKU Logo"></a>
						<a href="{% url "showfront:home" %}" class="retina-logo" data-dark-logo="{% static "showfront/images/logo-dark@2x.png" %}"><img src="{% static "showfront/images/logo@2x.png" %}" alt="NCKU Logo"></a>
					</div><!-- #logo end -->

					<!-- Primary Navigation
					============================================= -->
					<nav id="primary-menu">

						<ul>
							<li><a href="{% url "showfront:home" %}"><div>Home</div></a>
							
							</li>
							<li class="current"><a href="{% url "showfront:technology" %}"><div>Technology</div></a>
							
							</li>
                            
                           <li><a href="{% url "backend:backend_login" %}"><div>Admin</div></a>
							
							</li>
                            
                            <li><a href="{% url "showfront:about" %}"><div>About Us</div></a>
							
							</li>
                            
							
						</ul>

					

						

					</nav><!-- #primary-menu end -->

				</div>

			</div>

		</header><!-- #header end -->

		<!-- Page Title
		============================================= -->
		<section id="page-title" class="page-title-parallax page-title-dark" style="background-image: url('{% static "showfront/images/parallax/tech.jpg" %}'); padding: 120px 0;" data-stellar-background-ratio="0.3">

			<div class="container clearfix aligncenter">
				<h1>Technology</h1>
				<span>Innovations that could change the World</span>
			
			</div>

		</section><!-- #page-title end -->

		<!-- Content
		============================================= -->
		<section id="content">

			<div class="content-wrap">

				<div class="container clearfix" id="tech-post">

					<!-- Posts
					============================================= -->
					<div id="posts" class="post-grid clearfix">

					<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">Bluetooth low energy </a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2016</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

					<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

					<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

					<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

						<div class="entry clearfix">
							<div class="entry-image">
								<iframe width="560" height="315" src="http://www.youtube.com/embed/SZEflIVnhH8" frameborder="0" allowfullscreen></iframe>
							</div>
							<div class="entry-title">
								<h2><a href="blog-single-full.html">This is a Standard post with a Youtube Video</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 30th Apr 2014</li>
								<li><a href="blog-single-full.html#comments"><i class="icon-comments"></i> 34</a></li>
								<li><a href="#"><i class="icon-film"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="blog-single-full.html"class="more-link">Read More</a>
							</div>
						</div>

						<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

						<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

						<div class="entry clearfix">
							<div class="entry-image">
								<a href="{% static "showfront/images/blog/full/1.jpg" %}" data-lightbox="image"><img class="image_fade" src="{% static "showfront/images/blog/grid/1.jpg" %}" alt="Standard Post with Image"></a>
							</div>
							<div class="entry-title">
								<h2><a href="{% url "showfront:blog" %}">This is a Standard post with Preview Image</a></h2>
							</div>
							<ul class="entry-meta clearfix">
								<li><i class="icon-calendar3"></i> 5th May 2014</li>
								
								<li><a href="#"><i class="icon-camera-retro"></i></a></li>
							</ul>
							<div class="entry-content">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptatem, dolorem animi nisi autem blanditiis enim culpa reiciendis et explicabo tenetur!</p>
								<a href="{% url "showfront:blog" %}" class="more-link">Read More</a>
							</div>
						</div>

					</div><!-- #posts end -->

					<!-- Pagination
					============================================= -->
					<div style="text-align: center;"><ul class="pagination nobottommargin">
						<li class="disabled"><a href="#">&laquo;</a></li>
						<li class="active"><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li><a href="#">&raquo;</a></li>
					</ul></div>

				</div>

			</div>

		</section><!-- #content end -->

	<!-- Footer
		============================================= -->
		<footer id="footer" class="dark">

			

			<!-- Copyrights
			============================================= -->
			<div id="copyrights">

				<div class="container clearfix">

					<div class="col_half">
						Copyrights &copy; 2016 All Rights Reserved by ITLab-IoT team | NCKU.<br>
						

					

				</div>
<div class="col_half col_last tright">
						
<i class="icon-envelope2"></i> steven.ncku@gmail.com
						
					</div>
			</div><!-- #copyrights end -->

		</footer><!-- #footer end -->

	</div><!-- #wrapper end -->

	<!-- Go To Top
	============================================= -->
	<div id="gotoTop" class="icon-angle-up"></div>

	<!-- Footer Scripts
	============================================= -->
	<script type="text/javascript" src="{% static "showfront/js/functions.js" %}"></script>

</body>
</html>