backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name="backend"
urlpatterns = [
    url(r'index/$', views.List_user, name='backend_index'),
    url(r'api-info/$', views.Api_iot, name='backend_api'),
    url(r'account/$', views.Acc_manager, name='backend_account'),
    url(r'login/$', views.Login, name='backend_login'),
    url(r'detail/(?P<node_id>[0-9]+)/$', views.Admin_detail, name='backend_detail'),
]

fog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('iotnode.urls')),
    url(r'^', include('showfront.urls')),
    url(r'^backend/', include('backend.urls')),
]

showfront/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name="showfront"
urlpatterns = [
    url(r'^home/$', views.Home, name='home'),
    url(r'^technology/$', views.Technology, name='technology'),
    url(r'^blog/$', views.Technology_single, name='blog'),
    url(r'^about/$', views.About, name='about'),
]

backend/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backend/views.py
from django.core.paginator import  Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from iotnode.models import NodeInfo, TokenTable, NodeData,FileData
import datetime
# Create your views here.
@csrf_exempt
def Admin_detail(request,node_id):
    node_info = get_object_or_404(NodeInfo,pk=node_id)
    #print node_info.pk
    token_info =TokenTable.objects.get(node_id=node_id)
    #print token_info,type(token_info)
    try:
        node_data = NodeData.objects.get(node_id=node_id)
        #print node_data
        return render(request, 'backend/index.html',{"node_info": node_info,
                                                     "node_data": node_data,
                                                     "token_info": token_info})
    except:
        return render(request, 'backend/index.html',{"node_info": node_info,
                                                     "token_info": token_info})


@csrf_exempt
def Api_iot(request):
    return render(request, 'backend/api.html')

@csrf_exempt
def Acc_manager(request):
    return render(request, 'backend/acc-m.html')

@csrf_exempt
def Login(request):
    return render(request, 'backend/login.html')

@csrf_exempt
def List_user(request):
    iot_node_list = NodeInfo.objects.all()
    register_code=[]
    for i in iot_node_list:
        now = datetime.datetime.now()
        if now <= (i.timestamp+datetime.timedelta(days=i.service_limitation)):
            status_code = 1
        else:
            status_code = 0
        register_code.append(status_code)
    paginator = Paginator(iot_node_list,10)
    page = request.GET.get('page')

    try:
        node_show = paginator.page(page)
    except PageNotAnInteger:
        node_show = paginator.page(1)
    except EmptyPage:
        node_show = paginator.page(paginator.num_pages)

    return render(request, 'backend/node-list.html', {'node_show':node_show,'register_code':register_code})

backend/templates/backend/login.html
{% load staticfiles  %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="ITLab-IoT team | NCKU">
		<meta name="author" content="ITLab-IoT team | NCKU">

		<link rel="shortcut icon" href="{% static "backend/assets/images/favicon.ico" %}">

		<title>ITLab-IoT team | NCKU</title>

		<link href="{% static "backend/assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/core.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/components.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/icons.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/pages.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/responsive.css" %}" rel="stylesheet" type="text/css" />
         <link href="{% static "backend/assets/css/2016.css" %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static "backend/assets/js/modernizr.min.js" %}"></script>

	</head>
	<body>

        <div class="animationload">
            <div class="loader"></div>
        </div>

		<div class="account-pages"></div>
		<div class="clearfix"></div>
		
		<div class="wrapper-page">
			<div class="card-box">
				<div class="panel-heading logo-image"> <a href="{% url "showfront:home" %}"><img src="{% static "backend/images/logo-lg.png" %}" alt=""/></a> </div>

				<div class="panel-body">
					<form class="form-horizontal m-t-20" action="{% url "backend:backend_index" %}">

						<div class="form-group ">
							<div class="col-xs-12">
								<input class="form-control" type="text" required="" placeholder="Username">
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-12">
								<input class="form-control" type="password" required="" placeholder="Password">
							</div>
						</div>

					

					  <div class="form-group text-center m-t-40">
							<div class="col-xs-12">
								<button class="btn btn-warning btn-block btn-lg text-uppercase waves-effect waves-light" type="submit">
									Log In
								</button>
							</div>
						</div>

						<div class="form-group m-t-20 m-b-0">
							<div class="col-sm-12">
								<a href="page-recoverpw.html" class="text-dark" data-toggle="modal" data-target="#con-close-modal"><i class="fa fa-lock m-r-5"></i> Forgot your password?</a>
							</div>
						</div>
						
						<div class="form-group m-t-20 m-b-0">
							<div class="col-sm-12 text-center">
								<h4><b>Sign in with</b></h4>
							</div>
						</div>
						
						<div class="form-group m-b-0 text-center">
							<div class="col-sm-12" id="social-login">
								<button type="button" class="btn w-lg btn-facebook waves-effect waves-light m-t-20">
		                           <i class="fa fa-facebook m-r-5"></i> Facebook
		                        </button>

		                     

	                          <button type="button" class="btn w-lg btn-googleplus waves-effect waves-light m-t-20">
		                           <i class="fa fa-google-plus m-r-5"></i> Google+
		                        </button>
							</div>
						</div>
					</form>

				</div>
			</div>
			<div class="row">
				<div class="col-sm-12 text-center">
					<p>
						Copyrights &copy; 2016 All Rights Reserved <br>ITLab-IoT team | NCKU
					</p>
				</div>
			</div>

		</div>
        
                         <div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h4 class="modal-title">Forgot Your Password</h4>
                                        </div>
                                        <div class="modal-body">
                                           
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label for="field-3" class="control-label">Email</label>
                                                        <input type="text" class="form-control" id="field-3" placeholder="xxxxxx@mail.com">
                                                        <span class="help-block"><small></small>enter your email address and we'll send you the password</span>
                                                    </div>
                                                </div>
                                            </div>
                                      
                                        </div>
                                        <div class="modal-footer">
                                        
                                            <button type="button" class="btn btn-success waves-effect waves-light">Send</button>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.modal -->

		<script>
			var resizefunc = [];
		</script>

		<!-- jQuery  -->
        <script src="{% static "backend/assets/js/jquery.min.js" %}"></script>
        <script src="{% static "backend/assets/js/bootstrap.min.js" %}"></script>
        <script src="{% static "backend/assets/js/detect.js" %}"></script>
        <script src="{% static "backend/assets/js/fastclick.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.slimscroll.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.blockUI.js" %}"></script>
        <script src="{% static "backend/assets/js/waves.js" %}"></script>
        <script src="{% static "backend/assets/js/wow.min.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.nicescroll.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.scrollTo.min.js" %}"></script>


        <script src="{% static "backend/assets/js/jquery.core.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.app.js" %}"></script>

	</body>
</html>

backend/templates/backend/node-list.html
{% load staticfiles  %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <meta name="description" content="ITLab-IoT team | NCKU">
        <meta name="author" content="ITLab-IoT team | NCKU">

        <link rel="shortcut icon" href="{% static "backend/assets/images/favicon.ico" %}">

        <title>ITLab-IoT team | NCKU</title>

        <!-- Magnific popup Css-->
        <link rel="stylesheet" href="{% static "backend/assets/plugins/magnific-popup/dist/magnific-popup.css" %}" />
        <!-- Datatables-editable Css-->
        <link rel="stylesheet" href="{% static "backend/assets/plugins/jquery-datatables-editable/datatables.css" %}" />

        <link href="{% static "backend/assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/core.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/components.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/icons.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/pages.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/menu.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/responsive.css" %}" rel="stylesheet" type="text/css" />
        <link href="{% static "backend/assets/css/2016.css" %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static "backend/assets/js/modernizr.min.js" %}"></script>

    </head>


    <body>


        <!-- Navigation Bar-->
        <header id="topnav">
            <div class="topbar-main">
                <div class="container">

                    <!-- Logo container-->
                    <div class="logo">
                        <a href="{% url "backend:backend_index" %}" class="logo"><img src="{% static "backend/images/logo-dark.png" %}" alt=""/></a>
                    </div>
                    <!-- End Logo container-->

                    <div class="menu-extras">

                         <ul class="nav navbar-nav navbar-right pull-right">
                        
                          <li id="btn-front-pc">
                                <a href="{% url "backend:backend_index" %}" class="waves-effect waves-light" aria-expanded="true">
                                    <i class="icon-home"></i> 
                                </a>
                           
                            </li>
                         
                             <li class="dropdown">
                                <a href="" class="dropdown-toggle waves-effect waves-light profile" data-toggle="dropdown" aria-expanded="true"><img src="{% static "backend/assets/images/users/avatar-1.jpg" %}" alt="user-img" class="img-circle"> </a>
                                <ul class="dropdown-menu">
                                 <li id="btn-front-mobile"><a href="{% url "showfront:home" %}"><i class="ti-home m-r-5"></i> Front End</a></li>
                                    <li><a href="{% url "backend:backend_login" %}"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                                </ul>
                            </li>

                        
                        </ul>

                        <div class="menu-item">
                            <!-- Mobile menu toggle-->
                            <a class="navbar-toggle">
                                <div class="lines">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                            </a>
                            <!-- End mobile menu toggle-->
                        </div>
                    </div>

                </div>
            </div>
            <!-- End topbar -->


            <!-- Navbar Start -->
            <div class="navbar-custom">
                <div class="container">
                <div id="navigation">
                    <!-- Navigation Menu-->
                    <ul class="navigation-menu">
                        <li class="active">
                            <a href="{% url "backend:backend_index" %}"><i class="md md-cloud-queue"></i>IoT Device</a>
                          
                        </li>
                        <li>
                            <a href="{% url "backend:backend_api" %}"><i class="md md-settings-applications"></i>API</a>
                           
                        </li>


                        <li >
                            <a href="{% url "backend:backend_account" %}"><i class="md md-account-child"></i>Accounts</a>
                           
                        </li>
                       

               
                    </ul>
                    <!-- End navigation menu        -->
                </div>
            </div>
            </div>
        </header>
        <!-- End Navigation Bar-->


        <!-- =======================
             ===== START PAGE ======
             ======================= -->

        <div class="wrapper">
            <div class="container">

                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                    
                        <h4 class="page-title">IoT Nodes Management</h4>
                       

                    </div>
                </div>
                <!-- Page-Title -->

                <div class="panel m-t-20">

                    <div class="panel-body">
                        <div class="" id="acc-m">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>User Name</th>
                                        <th>Register Date</th>
                                        <th>Service Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for node in node_show %}
                                    <tr >
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ node.node_user|upper }}</td>
                                        <td>{{ node.timestamp }}</td>
                                        {% if register_code %}
                                            <td><a href="{% url 'backend:backend_detail' node.id %}">Servicing</a> </td>
                                        {% else %}
                                            <td>Finished</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}



                                </tbody>
                            </table>
                        </div>
                    <div class ="pager">
                        <span class="step-links">
                            {% if node_show.has_previous %}
                            <a href="?page={{ node_show.previous_page_number }}">Previous</a>
                            {% endif %}

                            <span  class="current">
                             Page {{ node_show.number }} of {{ node_show.paginator.num_pages }}
                            </span>
                            {% if node_show.has_next %}
                            <a href="?page={{ node_show.next_page_number }}">Next</a>
                            {% endif %}
                        </span>
                    </div>

                    </div>
                    <!-- end: page -->

                </div> <!-- end Panel -->





             <!-- Footer -->
                <footer class="footer text-right">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-6">
                                2016 © ITLab-IoT team | NCKU.
                            </div>
                            <div class="col-xs-6">
                                <ul class="pull-right list-inline m-b-0">
                                    
                                    <li>
                                        <i class="fa fa-envelope-o"></i> steven.ncku@gmail.com
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- End Footer -->

            </div> <!-- end container -->
        </div>
        <!-- End wrapper -->



        <!-- jQuery  -->
        <script src="{% static "backend/assets/js/jquery.min.js" %}"></script>
        <script src="{% static "backend/assets/js/bootstrap.min.js" %}"></script>
        <script src="{% static "backend/assets/js/detect.js" %}"></script>
        <script src="{% static "backend/assets/js/fastclick.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.slimscroll.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.blockUI.js" %}"></script>
        <script src="{% static "backend/assets/js/waves.js" %}"></script>
        <script src="{% static "backend/assets/js/wow.min.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.nicescroll.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.scrollTo.min.js" %}"></script>

        <script src="{% static "backend/assets/js/jquery.core.js" %}"></script>
        <script src="{% static "backend/assets/js/jquery.app.js" %}"></script>

        <!-- Examples -->
	    <script src="{% static "backend/assets/plugins/magnific-popup/dist/jquery.magnific-popup.min.js" %}"></script>
	    <script src="{% static "backend/assets/plugins/jquery-datatables-editable/jquery.dataTables.js" %}"></script>
	    <script src="{% static "backend/assets/plugins/datatables/dataTables.bootstrap.js" %}"></script>
	    <script src="{% static "backend/assets/plugins/tiny-editable/mindmup-editabletable.js" %}"></script>
	    <script src="{% static "backend/assets/plugins/tiny-editable/numeric-input-example.js" %}"></script>
<!--
	    <script src="{% static "backend/assets/pages/datatables.editable.init.js" %}"></script>

	    <script>
			$('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();

		</script>
-->
    </body>
</html>